=== GNOME/gnome-i18n/status/data/translation-status.dtd
<!ELEMENT translation-status (release*, module*) >
<!ATTLIST translation-status
  xmlns CDATA #FIXED 'http://developer.gnome.org/projects/gtp/status/translation-status.dtd' >

<!ELEMENT release (group*) >
<!ATTLIST release name ID #REQUIRED >

<!ELEMENT group (description, essential?, frozen?) >
<!ATTLIST group name ID #REQUIRED >

<!ELEMENT description (#PCDATA) >
<!ELEMENT essential EMPTY >
<!ELEMENT frozen EMPTY >

<!ELEMENT module (version*) >
<!ATTLIST module name CDATA #REQUIRED >

<!ELEMENT version (component*) > 
<!ATTLIST version release IDREF #REQUIRED >

<!ELEMENT component (podir, potname, branch, regenerate?, download?, nextrelease?) >
<!ATTLIST component name CDATA #REQUIRED >
<!ATTLIST component dir CDATA #REQUIRED >
<!ATTLIST component group IDREF #REQUIRED >

<!ELEMENT podir EMPTY >
<!ATTLIST podir dir CDATA #REQUIRED >

<!ELEMENT potname EMPTY >
<!ATTLIST potname name CDATA #REQUIRED >

<!ELEMENT branch EMPTY >
<!ATTLIST branch name NMTOKEN #REQUIRED >

<!ELEMENT regenerate EMPTY >

<!ELEMENT download EMPTY >

<!ELEMENT nextrelease EMPTY >
<!ATTLIST nextrelease date CDATA #REQUIRED >

=== GNOME/gnome-i18n/status/translation-status-extra.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE translation-status SYSTEM "translation-status.dtd" >

<translation-status>

  <release name="gnome-2.0-extras" >
    <maintitle>GNOME translation status - GNOME 2.0 Extra</maintitle>
    <mainhead>
      GNOME translation status - GNOME 2.0 Extra

      This table shows the GNOME translation status for the GNOME 2.0 Extra software.
      All data is shown as percentage of translated messages and you
      could download the latest .po &amp;&amp; .pot files from this page.
    </mainhead>
    <mainfoot></mainfoot>
  </release>

  <module name="anjuta2">
    <version release="gnome-2.0-extras">
      <component name="anjuta2" dir="anjuta2">
        <podir dir="po"/>
        <potname name="anjuta2.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="atomix">
    <version release="gnome-2.0-extras">
      <component name="atomix" dir="atomix">
        <podir dir="po"/>
        <potname name="atomix.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="balsa">
    <version release="gnome-2.0-extras">
      <component name="balsa" dir="balsa">
        <podir dir="po"/>
        <potname name="balsa.pot"/>
        <branch name="BALSA_2"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="dia">
    <version release="gnome-2.0-extras">
      <component name="dia" dir="dia">
        <podir dir="po"/>
        <potname name="dia.pot"/>
        <branch name="TARGET_GTK2_0"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="ggv">
    <version release="gnome-2.0-extras">
      <component name="ggv" dir="ggv">
        <podir dir="po"/>
        <potname name="ggv.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="ghex">
    <version release="gnome-2.0-extras">
      <component name="ghex" dir="ghex">
        <podir dir="po"/>
        <potname name="ghex-2.0.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="gimp">
    <version release="gnome-2.0-extras">
      <component name="gimp" dir="gimp">
        <podir dir="po"/>
        <potname name="gimp14.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
      </component>
      <component name="gimp-freetype" dir="gimp-freetype">
        <podir dir="po"/>
        <potname name="gimp14-freetype.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
      <component name="gimp-perl" dir="gimp">
        <podir dir="plug-ins/perl/po"/>
        <potname name="gimp14-perl.pot"/>
        <branch name="HEAD"/>
      </component>
      <component name="gimp-libgimp" dir="gimp">
        <podir dir="po-libgimp"/>
        <potname name="gimp14.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
      </component>
      <component name="gimp-plug-ins" dir="gimp">
        <podir dir="po-plug-ins"/>
        <potname name="gimp14.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
      </component>
      <component name="gimp-script-fu" dir="gimp">
        <podir dir="po-script-fu"/>
        <potname name="gimp14.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
      </component>
    </version>
  </module>
  <module name="gnome-db">
    <version release="gnome-2.0-extras">
      <component name="gnome-db" dir="gnome-db">
        <podir dir="po"/>
        <potname name="gnomedb-2.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="gnome-pim">
    <version release="gnome-2.0-extras">
      <component name="gnome-pim" dir="gnome-pim">
        <podir dir="po"/>
        <potname name="gnome-pim.pot"/>
        <branch name="gnome-pim-2-branch"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="gnome-spell">
    <version release="gnome-2.0-extras">
      <component name="gnome-spell" dir="gnome-spell">
        <podir dir="po"/>
        <potname name="gnome-spell.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="gnomemeeting">
    <version release="gnome-2.0-extras">
      <component name="gnomemeeting" dir="gnomemeeting">
        <podir dir="po"/>
        <potname name="gnomemeeting.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="gnomoku">
    <version release="gnome-2.0-extras">
      <component name="gnomoku" dir="gnomoku">
        <podir dir="po"/>
        <potname name="gnomoku.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="gok">
    <version release="gnome-2.0-extras">
      <component name="gok" dir="gok">
        <podir dir="po"/>
        <potname name="gok.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="gperfmeter">
    <version release="gnome-2.0-extras">
      <component name="gperfmeter" dir="gperfmeter">
        <podir dir="po"/>
        <potname name="gperfmeter.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="gnumeric">
    <version release="gnome-2.0-extras">
      <component name="gnumeric" dir="gnumeric">
        <podir dir="po"/>
        <potname name="gnumeric.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="gtranslator">
    <version release="gnome-2.0-extras">
      <component name="gtranslator" dir="gtranslator">
        <podir dir="po"/>
        <potname name="gtranslator.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="libgda">
    <version release="gnome-2.0-extras">
      <component name="libgda" dir="libgda">
        <podir dir="po"/>
        <potname name="libgda-2.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="libgnomedb">
    <version release="gnome-2.0-extras">
      <component name="libgnomedb" dir="libgnomedb">
        <podir dir="po"/>
        <potname name="libgnomedb-2.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="memprof">
    <version release="gnome-2.0-extras">
      <component name="memprof" dir="memprof">
        <podir dir="po"/>
        <potname name="memprof.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="metacity">
    <version release="gnome-2.0-extras">
      <component name="metacity" dir="metacity">
        <podir dir="po"/>
        <potname name="metacity.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="nautilus-mozilla">
    <version release="gnome-2.0-extras">
      <component name="nautilus-mozilla" dir="nautilus-mozilla">
        <podir dir="po"/>
        <potname name="nautilus-mozilla.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="radioactive">
    <version release="gnome-2.0-extras">
      <component name="radioactive" dir="radioactive">
        <podir dir="po"/>
        <potname name="radioactive.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="ximian-setup-tools">
    <version release="gnome-2.0-extras">
      <component name="ximian-setup-tools" dir="ximian-setup-tools">
        <podir dir="po"/>
        <potname name="ximian-setup-tools.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
  <module name="xscreensaver">
    <version release="gnome-2.0-extras">
      <component name="xscreensaver" dir="xscreensaver">
        <podir dir="po"/>
        <potname name="xscreensaver.pot"/>
        <branch name="HEAD"/>
        <regenerate/>
        <download/>
      </component>
    </version>
  </module>
</translation-status>
